services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Asdfqwerty123
    volumes:
      - mongo-data:/data/db

  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress-local
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      # connect via service name "mongodb"
      ME_CONFIG_MONGODB_URL: ${DOCKER_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:
