from beanie import Document
from pydantic import BaseModel, Field
from typing import List
from datetime import date
from uuid import UUID, uuid4


class ItineraryDay(BaseModel):
    # A single day's events in the itinerary
    date: date
    event_type: str  # e.g., "dental_procedure", "tourism_activity", "recovery"
    description: str
    location: str
    estimated_cost: float = Field(..., ge=0)


class Itinerary(Document):
    # Full itinerary generated by the AI
    itinerary_id: UUID = Field(default_factory=uuid4)
    user_id: str
    dentist_id: str
    days: List[ItineraryDay]
    total_estimated_cost: float = Field(..., ge=0)
    generated_by_ai: bool

    class Settings:
        name = "itineraries"
