from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date


class ItineraryDay(BaseModel):
    # A single day's events in the itinerary
    date: date
    event_type: str  # e.g., "dental_procedure", "tourism_activity", "recovery"
    description: str
    location: str
    estimated_cost: float = Field(..., ge=0)


class Itinerary(BaseModel):
    # Full itinerary generated by the AI
    itinerary_id: str
    user_id: str
    dentist_id: str
    days: List[ItineraryDay]
    total_estimated_cost: float = Field(..., ge=0)
    generated_by_ai: bool
